// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnzy8eyRCF7IWaDHWcV_2cUJvECIjEVho',
    appId: '1:205856408979:web:3dc346d23e618e940d5466',
    messagingSenderId: '205856408979',
    projectId: 'halo-safety',
    authDomain: 'halo-safety.firebaseapp.com',
    storageBucket: 'halo-safety.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-zrSKgqkxbDSNKqZlbZrnY915NEX4e9c',
    appId: '1:205856408979:android:92208dddb656bb430d5466',
    messagingSenderId: '205856408979',
    projectId: 'halo-safety',
    storageBucket: 'halo-safety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmLHmd7Y17JbW4a_011rT3yNhWzxA3q_U',
    appId: '1:205856408979:ios:5190ac0cb390911e0d5466',
    messagingSenderId: '205856408979',
    projectId: 'halo-safety',
    storageBucket: 'halo-safety.firebasestorage.app',
    iosBundleId: 'com.example.haloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmLHmd7Y17JbW4a_011rT3yNhWzxA3q_U',
    appId: '1:205856408979:ios:5190ac0cb390911e0d5466',
    messagingSenderId: '205856408979',
    projectId: 'halo-safety',
    storageBucket: 'halo-safety.firebasestorage.app',
    iosBundleId: 'com.example.haloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnzy8eyRCF7IWaDHWcV_2cUJvECIjEVho',
    appId: '1:205856408979:web:e8a287f220e553800d5466',
    messagingSenderId: '205856408979',
    projectId: 'halo-safety',
    authDomain: 'halo-safety.firebaseapp.com',
    storageBucket: 'halo-safety.firebasestorage.app',
  );
}
